apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Owr0o11++hqqAODrKGwbMo1cgs6g5+4=,iv:uPwX6064/9cF9P8x7bXuBBy552U4bpY6iJke81ZVbhM=,tag:65vhvPMEkHcuLfLRkcxZqA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:Bjw=,iv:EPRNaqgVnwY2P9g0UaxUF0JmlEsSTmwpi9M+rb4mk0I=,tag:3KuKPDO92VbaxEEWHqZ8jA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:X0EiAjaC7IC6d0OJ9LQ=,iv:dn0ait4idfZR4armKU8Doq/VjCiF1obqU++NkBkQ+Z0=,tag:d4MG4lnqaU2vjtsepRVoOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age134zrrympzafscksx92eny0t03l3gv84pe7v992h27k4rdlcveakqwklge0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdEoyRWFzT3RzREEvT3RP
            S0ROdjQxZ0FFdkJKWS9yb0hhd0NTUnBiMHdBClpVOHRrSVZIUkdQd0hOM1hoYXhL
            d1NONWRIbSs5N1RObVVETlJ5dHhrY3cKLS0tIFdrajIxaFVKZ0xua2pkV2pXb3Yr
            SlRRbm9KMlBGSlRPTGNVVUQ1QnpkbG8KqQ5WSI3d7RuCBOsCX9FMY9na4hSPAR8A
            uNZVwNqoTJQ+lXCOHJ1ykv9hFO5L2THXxnT56DSnJPHlMzyf1P/sQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-06T02:57:53Z"
    mac: ENC[AES256_GCM,data:CTNLzpa2QFV8fRSRZEbWqwc/CstXGZRUu272COqiQaNHDyo9h5qPN2Hr3k5/5Kxd1mPv7SmKs8ouiCuLL3sf8JOY8FdxzNTbOfvsjDKvVBmHEpwbeUuKtIicgnjrvE0QBG/g31HvzsLv1EdxlJgVESDz7UITES5F15v90cPdT/g=,iv:U6kBaflt0vZyOaL/y2OWg9aGotj/hxwz3X5QQWheUuQ=,tag:4hx8/nbCUtDZe+V9BagMhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
