---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age134zrrympzafscksx92eny0t03l3gv84pe7v992h27k4rdlcveakqwklge0
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age134zrrympzafscksx92eny0t03l3gv84pe7v992h27k4rdlcveakqwklge0
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age134zrrympzafscksx92eny0t03l3gv84pe7v992h27k4rdlcveakqwklge0
