---
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  KUBERNETES_DIR: "{{.PROJECT_DIR}}/kubernetes"

dotenv: [".config.env"]

env:
  KUBECONFIG: "{{.PROJECT_DIR}}/kubeconfig"

includes:
  cluster: .taskfiles/ClusterTasks.yml

tasks:

  configure:
    desc: Configure repository from env settings
    cmds:
      - ./configure