apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease

metadata:
  name: weave-gitops
  namespace: weave-gitops

spec:
  interval: 15m

  chart:
    spec:
      chart: weave-gitops
      version: 4.0.13
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system

  values:
    adminUser:
      create: true
      username: admin
    ingress:
      enabled: false
      annotations:
        hajimari.io/icon: sawtooth-wave
    service:
      annotations:
        tailscale.com/expose: "true"
    networkPolicy:
      create: false
    metrics:
      enabled: true
    rbac:
      create: true
      impersonationResourceNames: ["admin"]
    podAnnotations:
      secret.reloader.stakater.com/reload: weave-gitops-secret
  valuesFrom:
    - kind: Secret
      name: weave-gitops-secret
      valuesKey: adminPassword
      targetPath: adminUser.passwordHash
