---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: searxng
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: searxng
      sourceRef:
        kind: HelmRepository
        name: searxng
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    searxng:
      config:
        general:
          instance_name: "Search"
        server:
          method: "GET"
        search:
          autocomplete: "google"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-staging
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns.home.arpa/enabled: "true"
          hajimari.io/icon: mdi:search
        hosts:
          - host: &host "searxng.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: searxng-tls
    resources:
      requests:
        cpu: 5m
        memory: 10Mi
      limits:
        memory: 50Mi