apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:hvSgzBA1nHsI0lNNvNwGrDLxU7RE3UGszG86Q7xzPH7nCgNjVLvm/Q==,iv:7sc+P1vtEPcrrekcTXVVVwjYIYYot9WsDEHwYU6mXvA=,tag:1q9G+d8qUa1n0LD1bY8laQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age134zrrympzafscksx92eny0t03l3gv84pe7v992h27k4rdlcveakqwklge0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRzNENlBOdTlNNmducEpw
            MHpneFlJbTh4YWRnK2J3RjdmYVViSzBhakFjCkxtWFVTdVlyazNXcVFUU3owMFI5
            QVBuK1Y1clE1TUZqT1Blc1FLeXg5em8KLS0tIEdtQzZLYVh1SXBmS2laTGRwZTFD
            amNHZzAwdnFsbmNtSXVNOFMwa2lYcncKTjG4nTRYDtKPysnv/S6eSZBgmbMKz2hd
            FmiPnav7qVDFUam0H04rVt+eCUqXzCeFQsqs++rdJFPSeN9LSsUNTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-06T04:30:17Z"
    mac: ENC[AES256_GCM,data:U3qcJkbk6wbtPPZJ9jtkCqAu6wuGqAce/+si8u3R9ipawGlRFQbbKIWbUhi1MiWnAkKQs8htH3PeTh5ILVGB3jvcYUkXzIOAX1wUnaYOL7yhb6AkYugukf7KVKfaHpMeNaw/2csY4OolZpxm0aMGcYJPP4eYNyVOfMvrJyBA0XI=,iv:/E6NJW0zCD9C/+6ZgLAChmThconM8WheByn9dqPSVss=,tag:Giwk+qEYAK23SyrZQsHPpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
