apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:bjF5v2F3Zm0D8SQkcLeEcamvmrbx41Xevgsq7wIKaCblP9e1iNeAog==,iv:TxvoHUqFca3+JLXwJxj9U6KFY5OX6eXElmeBvsspEBk=,tag:5p+e9U4+xsBadpAtyPwrWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age134zrrympzafscksx92eny0t03l3gv84pe7v992h27k4rdlcveakqwklge0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUUs2WWZXdkdyTUl6YjJP
            WHlicWN5WnN3L3JNdE9WOUt4SDg0Mm9BQ2lJCmZBc3Y0dk83eWtxTHpqSUg0UnBW
            VGk1T0RpSGU1Rlp4cEpLWjFQbzM2RHMKLS0tIGQ1NC9VcGhrRGw4YzFwUkc5OHZB
            SFl6U3VhUE1mQkVrY05sZVFGZHdBNkUKvp8q5Ln1WuBE0V/4xR2mnHRHmUI1Kqu8
            CmmDU6neSsVb+AogPxHZqcTUtmcnLJ5rvijDtK/NJKkRbzQ0sJRP/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-07T18:41:22Z"
    mac: ENC[AES256_GCM,data:YwQav30Iy43okWnYMf9mJ+u9L/xYHBLn/6khS8yG9vYT5b2GZJP3uyE6bwELOdJSL3JLDR5a58I87yjqyyha952K3f0tU4mLWP8ZVEhLGehIkoU+kedP0Zm9Qe/NVokZrLO9gbFdCHD1dGw5CPaE6WJ8AhLcgO8PX2berG0JbOI=,iv:olt11/5gITVu8UPoTd+ZopQCfAqL3tVBbUM2UKeG2mI=,tag:FfaEuT8A0/L8vqOpTVGVBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
