apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Nfcj0PaudFtMmnU717ChNho/fyBfq2KX5caHApEsI9nYdQIVgFp+yQ==,iv:58NIDBzsCvBmYzf2i5xRpb0iHVu7x23BUU66OsUhjZI=,tag:6eKN1nCrkjj28ZcdI+ed4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age134zrrympzafscksx92eny0t03l3gv84pe7v992h27k4rdlcveakqwklge0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTFdQZHMvOFYzTEo0M0hF
            T096bnY2OHFLZ1RoSUt5VmwzbHJ2Qzc5TDM0CjJCcUo4QVlEWHNmOGFZV1FBdEhi
            Qml3Q3F4anlnckR0a0d0c0ZHOE8yUTAKLS0tIHYyZ05xcjRuaUpQa2ZDVUR2MHQ0
            ck10djk0OFUyRW1KcHQzamNMVG1Fb3MKvimu5Il1NZedgXci7TwZd/pQNAFTELFY
            4EPLV9shQuEw6CpVS3zANMTDFCXVFzrrhVdMctlN2LsZ+/pi4j+KNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-06T02:57:54Z"
    mac: ENC[AES256_GCM,data:edY1bN6jxTWaVHsNYF33hJl8XPkFG3vXO44C/PIL9699Apy4pRnthL0eQ3HuCDIL+SGT9iL4QiBC8+loxaZ43ScRqms7mt6XrBkhi/w1tDSlGGyLGw+RoolR14FbECL5MQHEzXzT3xXaJul+4ORr0Ke08dXpTTQZFXijMIROezg=,iv:74ssp8170Es6Q062+11I9S7jLSoHLY0BWMJ5BBQJX6I=,tag:fcddKog4y4FRNE/KxGH3Sw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
