apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease

metadata:
  name: searxng
  namespace: searxng

spec:
  interval: 15m

  chart:
    spec:
      chart: searxng
      sourceRef:
        kind: HelmRepository
        name: searxng
        namespace: flux-system

  values:
    searxng:
      config:
        general:
          instance_name: "Search"
        server:
          method: "GET"
        search:
          autocomplete: "google"
    ingress:
      main:
        enabled: false
        ingressClassName: traefik
        annotations:
          # traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          # cert-manager.io/cluster-issuer: letsencrypt-staging
          hajimari.io/icon: mdi:search
        hosts:
          - host: &host "searxng.traefik"
            paths:
              - path: /
                pathType: Prefix
        # tls:
        #   - hosts:
        #       - *host
        #     secretName: searxng-tls
    resources:
      requests:
        cpu: 5m
        memory: 10Mi
      limits:
        memory: 50Mi
