apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:qwE=,iv:T0VG4qZYfrGc2x56aXYtR1SajDJeYwtbcTJM3UW1aV8=,tag:qFZbVGpAO5UhmAq5NBnwhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age134zrrympzafscksx92eny0t03l3gv84pe7v992h27k4rdlcveakqwklge0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMjBmc05LYTJDWWEyOWZN
            VVY0VUVNWlBGaGpEamhXai9HUzVqL2J1a3dJCnVkZGpWMnUzNFlSYzR0Ukp5Qmd4
            cnRkMVlwZ0R3ZEpjVmFxNlBFYlA0c3cKLS0tIGtQVkVNV1VNR0pOdVhQTDZ3bnlO
            MXJOQ1BCMjdpbTI1N3F4VktaK3IxZ0EKwsPXvKth21XCDjRNC0BWlNNMiGaqods7
            3WFjLC/hnn5SWaFVqIG6kjOKBgc+h4714BO5yF2rW6moOrtx35JxRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-06T02:57:53Z"
    mac: ENC[AES256_GCM,data:Yaqt//HhoIKGOabuoPQTgQBglJNUNkmVl/JXN3h17qjYileTG8L8qBmxRqo1xzwXzCvhr1FsZ3kTCTevsVvDOlddoucsK+UZ/HN+Tvyf5cRB+6VFsweDJw7XZgXSLVEEH2w7FhmfUmoCs1K+2AWCiL7RPdQ9vzOXaz2dGzUZ9CI=,iv:B0S1zkkxIhEzcUCpwU1d1+qHE4k+eTA3/FOqSyeWdMQ=,tag:uTXdafFfksxcY0pVXwu7Wg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
