apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:YnseU2JUa2t3ULkZiME8BIypXvKzuERAwi61N2RL2sHIM4pUqQ==,iv:UfbhvFqV884gP8qtJV/2sYDxAL1Wsol22CMxxwMO0Uw=,tag:qlW10cpD0OOAgJZBgV4zvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age134zrrympzafscksx92eny0t03l3gv84pe7v992h27k4rdlcveakqwklge0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYnVMMi9RcCtlVzZBc085
            R2kyb1dGMnN6c2VDc2hnU0Q4SFBtb2YrbVRFCktBK0s1TVk1ekFGZDZmT0JKSmJE
            Z0tXK3I2RjdPSGg1Y2JML2g5SjA2VjgKLS0tIGhRTFZTcjkrZmphQ0VxY09ySkN1
            YmZGcUFvUjdDako5c2ZxdGdPUDRRRUUKs316+rcs5DptTWmqkBkXKCubh58HeeYN
            bpMMTsuBbu8vQBgutUT4pRNuM/Zq6QgDPaTntc8J/x9QLhxuoSuJMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-07T18:41:22Z"
    mac: ENC[AES256_GCM,data:NBhg0Bdw9oc+geBdc/VTKAztv4u4IJpscLG+EiY2gSS0I1CA7Ruyk62cYgV+DtF+8i9GmzXcA+7x/7ASy+MCh4+iVm9I2B6cCJqCpbvAM+8/92pWlCt6Sj9g8PqTIZmtiztzNw2D6T5kgJ2lfmlxI+428zLa+c+uV+hAB7f58zk=,iv:Ey1qz+Y+dbKeZWb877ZVXhRPEoinl0/nxX78SgXY0Bk=,tag:jriivF5McAoJOm34IUa4DA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
