apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease

metadata:
  name: contour-private
  namespace: contour-private

spec:
  interval: 1m

  chart:
    spec:
      chart: contour
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 10.1.3

  values:
    contour:
      manageCRDs: true
      ingressClass:
        name: private
        default: true
    envoy:
      useHostPort: false
      service:
        type: LoadBalancer
        loadBalancerClass: tailscale
        annotations:
          tailscale.com/hostname: "homelab"
