apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
stringData:
    client_id: ENC[AES256_GCM,data:pVsjglFl9+eonqYU,iv:SB+ydqIn7ef7IqBPpdppMEN6iWQ6ob9YkCId/nkAdL0=,tag:M811UgEIA91iS3GvxgMjKQ==,type:str]
    client_secret: ENC[AES256_GCM,data:bHKJEVcKEIldm0BHvJHQug4R1JfXhpozEId2Ku6RNue9K3It5Me0X3QadO1X9eA17UV4Cmpt71ZEoQ==,iv:8Ql43Vf6S7zLT2drYXgVAwTT/p3B3kscYfv9BK/SoB4=,tag:n2/Up/FLB6suqnlHHp8hsg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age134zrrympzafscksx92eny0t03l3gv84pe7v992h27k4rdlcveakqwklge0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NE4vcmlLdkpYSXNoYUt0
            RmI0M2RMRWFSWFFScTI5alpHaHpKdjNXWkVjCjBsVzVONlgzMVdNQVZoOWp1c2Vs
            Z1YzTk5zQ0R5MU5JejdmeDc3cmJpY0UKLS0tIHpMVG5GMExlTWJQODdWRzNTbk5P
            UCtQM3liQUJRUnNMQlJVenNMbHhhTHcKp3OPRmiwa/L1f+EJD/ywlQpK74XR53Uh
            vbuuRjjdylifmo08aBHYJHlUQpH1Rg8JLg4Ck3KvBeMY8mh3LsYwDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-05T00:03:55Z"
    mac: ENC[AES256_GCM,data:U9cuZPUB13u5toYSTXcws+/MoFQPbvM5F2/pn3frOIPtJ4ACZ3x0Ow/AQig1DMU6nUUamXL/+qdcPA35nCYfcYOSwJrZ+4fID7chO0Ya2Lw2kLZnZKmAuZrbtb5GSggKL4nxfvFQmvRaKd0nxsLn1rI/0N8tVFoo7fxyYuQ2bpo=,iv:IZvvnloK2qVAC+BoMuK2qrfhspTPK75awXC7uQ53pdc=,tag:XgCSvx+JSoqYTYE/Oh5kgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
