apiVersion: v1
kind: Secret
metadata:
    name: tailscale-config
    namespace: networking
stringData:
    TS_AUTH_KEY: ENC[AES256_GCM,data:epDiBVr6LIeAp/IMATHmhhF/Qnf5ck3cEsbd1iXX5TRQ30UX/PM/cy1WbA+ur+gD4+QlOJNGDSMl,iv:sxDTxCOmQXEZQyIqSw9oiZYF1JmfR82YFeSpVvToTeI=,tag:at1nyMdLlbxIIpFAemB0Lg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age134zrrympzafscksx92eny0t03l3gv84pe7v992h27k4rdlcveakqwklge0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OTdsclZWTVFzNXNVY3hy
            MTF4Witoc2RFWW4wMEsxTFJGcUZyYUpXMXhZCnN2MDM4Sjg2Wk52RktsVHFOU1I4
            SmZtOHFKZm1pWk5XaURLb0xLaG52emMKLS0tIHNVSDhNbnAvS0lLdWI5emlIalF4
            aXI0SXpZTVZLNkJqaWFIbTBwa05uNW8KWUxAfKNJ1WarfQ23iRpG36MMoX7WziMb
            a7fM9y0dI5krBFVsOS6+65d1jEPxfPGadtg97nXXtwXTHYYnwh9ETA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-31T06:11:33Z"
    mac: ENC[AES256_GCM,data:UphB/KXikWq6JfOSJIfbm/bNfj7xMjzAUITo9vBLP+xAiHfCtzrvjaHj8uJi3YIBpNMUeD1b2zs59w1+1OIIHYAqzETtnEyJ+U2LrstKhoOJUE4xI8KXZNin35zvfkdPOmWaiSo3mnfswpNWTMrxw2DNWgp92Cj58cV5zSZpijw=,iv:7aHQN1FY/YjAcY0Ai+yKZfDGz79cEXHJSupC3dnAOVw=,tag:FxtDnc6ZDm2p2pGsHHtjgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
