apiVersion: v1
kind: Secret
metadata:
    name: tailscale-config
    namespace: tailscale
stringData:
    TS_AUTH_KEY: ENC[AES256_GCM,data:zE4+VAZsfR1rZv6Vc7n0dGTJLQ3MY9hVFfcBxc2qnYuIIoJY2PrmQW2ziST53YQ+ZwT+VWJOfGc=,iv:Too3MTJUWgLJ6+/E9F5Ltfb51dW8UNBZOx6GsCoAfyI=,tag:LX8TIpb2lZJ7IZNbSOvV5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age134zrrympzafscksx92eny0t03l3gv84pe7v992h27k4rdlcveakqwklge0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRE5razZ5K1dqTWxLWGNW
            WE5qcCtHSTlUS2JoV0p3bTZUeERKNU5hejM4CllieHVWcGNmbzY3RHdnMUlTckVX
            WjZncDBrelpDS1lpcDl4R2ZXcjlHYXMKLS0tIHhFeWxwcjFOdGlxdUttQ29YcDRQ
            dmVBd1Z3K1pBZll1QVhPSmx1V2ZMQmsKxKgSKghavjJbQxszkT2LcogP+KG2BfgG
            w/Is2Db0fHSraST6Z9u5Ir1/cu2EoVrZy61nNsTx4Peh452/kcmmWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-31T21:14:36Z"
    mac: ENC[AES256_GCM,data:QjlKJRQHaLcVu5cFhtJq3fS3Mqgy13LIDk5nFMtXB5JA5u6HsI/sfgZ8n2RFw6JueKOVoFp98qJSVkLU6m8UOqDFMiw5Qwd34mkwLyhoMPO54TP9zu2NUvotW8PvQEgiYe54d2brdEIoS3jxBIqW9JJf5JwWrdHWb/SpToKrUhw=,iv:OC9q824ezqGfGuDFAaUr64YXvKERngjPHnr28f44FVc=,tag:0L8KUsZwz+0+Po4AGbBXrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
