apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease

metadata:
  name: traefik
  namespace: traefik

spec:
  interval: 1m

  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 20.8.0

  values:
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "traefik"
