apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease

metadata:
  name: traefik
  namespace: traefik

spec:
  interval: 1m

  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 20.8.0

  values:
    service:
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "traefik"
    globalArguments:
      - "--serverstransport.insecureskipverify=true"
      - "--providers.kubernetesingress.ingressclass=traefik"
    ports:
      web:
        redirectTo: websecure
      websecure:
        http3:
          enabled: true
        tls:
          enabled: true
          options: "default"
    providers:
      kubernetesCRD:
        ingressClass: traefik-private
        allowCrossNamespace: true
        allowExternalNameServices: true
