apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:t0V08v7Ckpo5T/Jg5G+JiHzUYzLp5L/KnQ7uQ3m4uIqkNW5WwNAyNFKk3micpLhTmRYEoJ/tGVdz/uxP,iv:WmCiws4JuWTYjuIINvHmUXWuX/vBnTDdV4l5Su+/ox8=,tag:81WH7CmQPdoUqnOl6vrBsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age134zrrympzafscksx92eny0t03l3gv84pe7v992h27k4rdlcveakqwklge0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeDlZVVlGL0kvSkVCaXk0
            QnpnN2E1K010Y3M4bTVwNE05Q090eGJzYzBnCnRZVWp3ZzV3WWR0a2RrOEtUSUpy
            ekZ0cElnS2lMRVhPcER5VloyWkdrK2MKLS0tIE9vMWlCV045NkV0RC9XajZPWHQ2
            UHNEMjRWT0duRHVrNE5paSszaWNtZEkK5ung62IUFSCtIJGbUlXnN0w0BWif9Yu9
            X+QX1E4P/rckWet2dV1tNg7jYFE0xEHuS2/oCgONM2+kZzG/1Ju27Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-07T18:41:22Z"
    mac: ENC[AES256_GCM,data:kSRyJZsgy4+s/4n46FgfOcYCwuej0ViKFLNJ1gu7AG02Tqh6FsCV9jbVgToPnQtPH88sUno6zLvN2Qhoo7OdqUKoAnmKjzGel/3shzZy4PTBJw6kInH5eADrx+qGxwGtgNxVu6nvVyLl/Z7AOMv7DAd3Ii6PZVLj8cZDtIXNj1M=,iv:o6sEViy18cb/3tgGwJbIKjciFRYuB/edwWDb49m7Ftg=,tag:HcnLd/TEq0nOPVspuTFeIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
