apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:US9Ir5H1POkF,iv:cqRchSjdSDusWsXl8Eknt/YgRBJe0ywGQ6Apm4NV6/g=,tag:eDlKblMnj37G4K+qNh/ejQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:C5KlZSVGPZDWT/RyL5bLqQw/tSEzXMI=,iv:X2JptaNu/8734v5Hz4FXznoLmzzScnEf6ok0CLnS77U=,tag:hSJMoTuma+ugNx9t/oxBgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age134zrrympzafscksx92eny0t03l3gv84pe7v992h27k4rdlcveakqwklge0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeXl4U3ZQOHFZQXJYd0NF
            UHFjTjhhWU9yVmpGb3BTVEhZc05FQi9xOENNCkF3RXFLSWxISlQ2VTZieXVVSGxt
            UzQ0ZHJCaVBiZnJHbW1Jd1AvSUI0MXMKLS0tIC8zK2tLWXk5WFIrSmZYK2I0a01l
            UTVqRmpnTDVPbE9NdnJXam5zdUFaNFUKZlwM/jV9LYhTePFkWoWvV3tbyFvKNPI0
            k6PI+26t2aXANcr6BZoD4Mj27DXvdd8iPr90WcAA+agY4rmm17vjNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-06T04:30:17Z"
    mac: ENC[AES256_GCM,data:YH3spDoxebslssBavGOAaXosXN12vZsHOn2SFlHWYN0EqlUU+X1CRg2cBPzle8Lulp6+KyagkIH+WHRaKJpDEJBoDZalXFTJhQ8Uiq13FzfuBxsc3OqSRb3Q0dyLFUw49fEtgUo5xpMyF7/FM30yuZ+Cg+2Imm1FMzcIZy8YEeA=,iv:gk76+AgQ2f77ZDbfwkPE5o9cZ34BADDG/vbDrVskDNs=,tag:wjHJXuOqy4RUunEf78c1Pg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
