apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:K9Ur1Kg0KDkT,iv:E4E9hMMoAck0GVsQyRgvuKw6ax+KZIO9wzqA1Hp27qk=,tag:4gWbcrPu3UVe0cY6Vct8cw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:JTmiEr1HWIcHPSt3dyp69J+sh7ED47o=,iv:cG9MPUONRY2tzie/0yQX8rK8gcBopn0uCTn9v66HCtw=,tag:3CxQOcICIXvGxEfkj7sxNQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ACCOUNT_TAG: ENC[AES256_GCM,data:+yRgn+wnWsjbfOi6MFjhWCXlpRLcfk9oAKmLGe/8zqA=,iv:xxhfhnbpZC5RGSp8XZJq2Y1vTWUkDsks0Aligb2tp7g=,tag:UcXa38BmjiU+HPh62KiV+Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_SECRET: ENC[AES256_GCM,data:UR9y/yiEDa/T8ouA83nVS61qUm0zIFDcVBi18wwSmJmT+O1xaIaQk0Yg+4M=,iv:x7NJGCsqgdyDtC8ApuFk9yVGSmYs/+4kSwKbPSDOBxw=,tag:8I9QqdaqyKqhiPPPIQyDhw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:yhSdzx0j4qb+ddLpqlVWkHT0Yt6/+ziUJZrUnnIi7kWs5u2D,iv:0KgblFwShH9UET7iGcvbAhDxS9YifnLUJtsLqzrXQZs=,tag:zLoahfBI7gh76Dwsz7wDhA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_NAME: ENC[AES256_GCM,data:kMaerdzhfN+fN70cPhA=,iv:O4lkw/MfJV4GpWsK3Z3GWg4kPXH4UpAcVeStzGENooM=,tag:rxKAu3iRmiPr9ODv5N2TMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age134zrrympzafscksx92eny0t03l3gv84pe7v992h27k4rdlcveakqwklge0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUlp1aDRyWGVvbGRyb3Ba
            L3NFMkQvVHo4SlpCMjlFcWU2OXdHeGZYTFJFCllnNE1VZW44aE81UVdlSEd2ZjN5
            MGc5NDgxWTA0WDl4WWlva0JjdW5lYVkKLS0tIGJWbmpVbTE4WjZmeDRZSVYvTEtO
            RjJSTUY2ZEtMNVQ0OUhLMndpd0RnMmcKSDt33QbP5VzwQ8pfICUOVi8v838xJvWi
            GYcgoSOs5r/W4i03JcSxaris26bq7YZNe5g0/A/2eYlrm9wGRnrm/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-07T18:41:22Z"
    mac: ENC[AES256_GCM,data:b7pWW51zxWbIC0WoLdeormB72GDupQw3N8Rq2zS0dTw0aSI5s58wCsqzHu/M23bmmJpwYOBo55A6+LGkoPPRTxu2rit+P76rchd/3oxvsHemFuuh7koJf7rTHlu5nGWTW8hWXqAkOD7na8R0017ZrSZ09MbKRzTTAYfRot46T1c=,iv:GSXJnFFJ9DjYPaV9HcbLwIn8bT/kyjrk3YdCWws72mM=,tag:IlM1v249woodhuQbu2FshQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
