apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:NxKDCsx5cHnI,iv:XMQ6tkm1k9Fx0qG0b2EKRgxpMSU9zBDleeAJBOwDn1w=,tag:/QmETXKG8G3zQznRzn/TxA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:5xN0OPO6wlBlCc7D0tEF8fs8fh7o/7Q=,iv:QuKDLL1HajqPzlWq1CJHjCHOkMvnbh8uWFQnbTHNAdo=,tag:jI1xJE/jbDGTharld0PQjw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ACCOUNT_TAG: ENC[AES256_GCM,data:98yhSqDBL/sd4ZZC6jAFqMbFIO0JoraOd1DYUQev1WI=,iv:NqIn7M4tXIOE+xHgk8vjZwcT5KdPgg9Fphr9VO8untk=,tag:tqrNlYvhmtHKT1PWnA8Heg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_SECRET: ENC[AES256_GCM,data:4JweDxU2R/DfHY9rzPrQPoRIrtU0ZX/U18PpImu5a4MzOPolzniVWcYPykw=,iv:pu9nJsYhjaPb6it9mX69Z7YRtTxAirK1wwqubOZgaqE=,tag:rjgvKaXf9f4ThNkm1DUmHw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:DT66i38/oy/6saeA//dLhJrrvuNypBpoDLN4RjWZBO48/BJr,iv:fAkY8ydVrZUPkXVFq0Ny67mSB3Fth84vWzRxmCnaaI0=,tag:cTFQQoctHB250WpPf4tH9w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_NAME: ENC[AES256_GCM,data:n6JkcNZ79tt6NVt1d3M=,iv:8zYAs0VamguENSHlLJ8tDT7owYINP6b+DeOILsg2xaU=,tag:HZZKYwQeSzbcaUF6F3VnGQ==,type:str]
    SECRET_TAILSCALE_AUTH_KEY: ENC[AES256_GCM,data:AzRDIVhzzoizO6BKxfuyoiv/j0IPw5eTotxt4oi2EDwhdTPnKcgvCwEf/y9ov6F+iwHP8HwxMHA=,iv:8BUgvQzFACa5zIBYCT9DbGYbIg/aiNabBIj4U5WrLrg=,tag:7RiI4msP5F8Ano2ZX2eJtQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age134zrrympzafscksx92eny0t03l3gv84pe7v992h27k4rdlcveakqwklge0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWStEOUFSc05ZczlBb0h0
            NEpYU0FWRHRRWUtDM2M5eVg0elJNYlVMYUJzCjBDZ1V2Q29QOG9tR28vOUtuTVhS
            TXQvQ243VmdPVy90RjZrUkJWQkhRM2sKLS0tIFpOMlhZVHBsVE9wbnZmeThzUjFk
            eldta3VZUHpiT3ZuREJHUzdmYkRZZUUKHsllXuDrnR/GN4nkzCb523rPX+tpY+7S
            HUbDjXWPEZ0T3680wpxFQk2iBLOWBj5IWjc0rS/qAOwoUFwM0ICO6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-20T07:07:05Z"
    mac: ENC[AES256_GCM,data:LIE4UedTBudQ86ysJQyFojUGX0TftJFjToT2RgxTGbq5dxg/1b2VsPUCdwMTgMF+DiyyErCaNFzZ6m8HJsDWcK1RUse6PeSk8Fk+5AeflQ5jJ01arusXYgyjvWfslB53jT1w4tIvhiIwMo4KzmILtyKeY3kcMaOAsKlEKZcYXUA=,iv:0ytRj8m4JJO4OsSAy6T4TgC+U3AYy9U1TRDb6eNphLM=,tag:l3G7N75YHmVsBGG/JgnUxQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
