apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:AeoxX6FtCaX0,iv:/8Xd/T/V0l8pmW2zGTqDsJQ1BS/f6JFsd1/kKr2GGbs=,tag:WJDy3tVfww5DMRvoJ6v8BQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Uk9nrqyLu7Aby4EkGbpWoXIUG5P+SPs=,iv:S/z2g36cqpozrngcsIlH3XdR/xY8JtIb9daQcd5hgkY=,tag:KRrzuSIGfx2tkJwEEgUxjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age134zrrympzafscksx92eny0t03l3gv84pe7v992h27k4rdlcveakqwklge0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbjdwRXArQm1EOFB3Y0NU
            SVdGbGUxUk1VVU5nVitVb2dGVTNqVThlV0JJCm1ieVlKUVI4V1hpQUlBc1JCZk5J
            N3R0bGFIVktTdUJZWlZ1YVJwQ3lKdUEKLS0tIHZRcmRuaXJhS1FlMjRwY0RWWHcw
            cWtRN0VJUzFQUzJiaHNybThpUGtTRTgKhrnV1xNkpVoSvIjiBqNjKMZNd8sB+nPs
            yGPVoQfuNVX1hFbiwu3HqzLZPgbrsc1f4mfH6a+hpDlfKQGSd6W/Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-06T04:47:03Z"
    mac: ENC[AES256_GCM,data:iN8LxqfNmluZD/ave+NzUFqd67oF6/RyPSmYQ4eTtg+wPtiEPG4WkUJ98kEYQWnXi9xsu43NnjVF8u7PdrGnk1XvzcO6BphenCwXbp1AFKsP1S99E2hhXtmOoHdP057RmgrLwUtw6Ku+bBBTqTcvUlC+bl8rqY+5ucOwuXcyUK0=,iv:oNJm3tVdo83Bu/wVD9/kTFmlCWBF7SKjRQW+PRe6CKo=,tag:b8UOFz6hdY1ww8a2dgPTTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
