apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease

metadata:
  name: hajimari
  namespace: hajimari

spec:
  interval: 15m

  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system

  values:
    hajimari:
      name: You
      title: Homelab
      lightTheme: gazette
      darkTheme: espresso
      alwaysTargetBlank: true
      showGreeting: true
      showAppGroups: true
      showAppStatus: true
      showBookmarkGroups: true
      showGlobalBookmarks: false
      showAppUrls: true
      defaultEnable: true
      namespaceSelector:
        matchNames:
          - default
      # defaultSearchProvider: Searxng
      # searchProviders:
      #   - name: Searxng
      #     token: s
      #     icon: mdi:search
      #     searchUrl: https://search.${SECRET_DOMAIN}/search?q={query}
      #     url: https://search.${SECRET_DOMAIN}
      customApps:
        - group: Media
          apps:
            - name: Element
              url: "https://app.element.io"
              icon: simple-icons:element
              info: Element/matrix webapp
            - name: Discord
              url: "https://discord.com/app"
              icon: simple-icons:discord
              info: Discord webapp
      globalBookmarks:
        - group: Media
          bookmarks:
            - name: YouTube
              url: "https://youtube.com"
            - name: Reddit
              url: "http://reddit.com"
            - name: Twitch
              url: "http://twitch.tv"
        - group: Dev
          bookmarks:
            - name: Codepen
              url: "https://codepen.io"
            - name: Devdocs
              url: "https://devdocs.io"
            - name: Devhints
              url: "https://devhints.io"
            - name: Carbon
              url: "https://carbon.now.sh"
            - name: Unicode Table
              url: "https://unicode-table.com"
    service:
      main:
        annotations:
          tailscale.com/expose: "true"
          tailscale.com/hostname: "hajimari"
    podAnnotations:
      configmap.reloader.stakater.com/reload: hajimari-settings
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 100m
        memory: 128M
