apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease

metadata:
  name: contour-private
  namespace: contour-private

spec:
  interval: 1m

  chart:
    spec:
      chart: contour
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 10.0.0

  values:
    contour:
      # Multiple deployments of contour will clash CRDs,
      # ensure only one chart manages them
      manageCRDs: true
      ingressClass:
        name: private
        default: false
    envoy:
      useHostPort: false
      service:
        type: ClusterIP
        externalTrafficPolicy: ""
        clusterIP: 10.43.0.60
