---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudflared
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: codechem
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    cloudflared:
      tunnelID: "${SECRET_CLOUDFLARE_TUNNEL_ID}"
      auth:
        tunnelName: "${SECRET_CLOUDFLARE_TUNNEL_NAME}"
        accountTag: "${SECRET_CLOUDFLARE_TUNNEL_ACCOUNT_TAG}"
        tunnelSecret: "${SECRET_CLOUDFLARE_TUNNEL_SECRET}"
      ingress:
        - hostname: "*.${SECRET_DOMAIN}"
          service: https://ingress-nginx.networking.svc.cluster.local:443
          originRequest:
            originServerName: "${SECRET_DOMAIN}"
        - service: http_status:404