---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudflared
      version: 0.1.2
      sourceRef:
        kind: HelmRepository
        name: xunholy
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: raspbernetes/cloudflared
      tag: "2022.12.1"
    cloudflared:
      tunnelID: "${SECRET_CLOUDFLARE_TUNNEL_ID}"
      existingSecret: cloudflared-secret
      ingress:
        - hostname: "*.${SECRET_DOMAIN}"
          service: https://ingress-nginx.networking
          originRequest:
            noTLSVerify: true
        - service: http_status:404