apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
type: Opaque
stringData:
    credential.json: ENC[AES256_GCM,data:yBMb7IRm2eRR6V1S12XEGA/+hRhMKf2p3PJaGKLza5TF/GNjeLX+MR++1oMrFAgDAa8V+TAf86O8exs57TWwPWFE9oL5cG7YJ/X9KKpw0n5hKilZEeWrhpA08Lf4a82JVwTj5sZiQFhvTdcin1Jx0LnQlBWUYiIWINXLj1WXyDySqNfv9gjzyEszb90Hd98d47YXxdl6tmqoSWh4RrpHLJ9rqb3q0g71zusdyuxqgdSZfPtRCl41DsgtS8mIsnIi2OaMyF9a3nB//XLOkw3+7w==,iv:1/9Drq2s1LnWuXYpQXA5bzULkdBeRrXI80jGD6/YM7I=,tag:1nND8791l/Bbyn56PrBpAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age134zrrympzafscksx92eny0t03l3gv84pe7v992h27k4rdlcveakqwklge0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQ2Q5VkdXUDduVFgxTEUx
            SkRsQTh5MDBhMEQxZkw2WmNCazNwdEp5ZENRCm55MjdkcnJSU0IwU3orVTB5aVQ0
            c05WdXNZeVAycmFXbGJFVzMvUkRLNUEKLS0tIGxqWnBMMnlPenhkOG9ERXNjUTBM
            ZkpvS0hDbXR6dU05a0piRFdaSzA2cmsKBBItn0/7DP2LHaCYpZCCJAPXRjmvGoUf
            4mK+DIhokOT0FS6yZKoodZ64ECmJKT9VavQE/0Nr2GqOECfhhXPk6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-07T18:41:22Z"
    mac: ENC[AES256_GCM,data:y1zEvFM6cLRQBB+/SbyWHq95R3HnbE14c6VGUBYgJKFriyfSMI7l+PrhnRFJmkjP+9cVlukzQNGHlZXO1AxcwBD42XyRt0KAkXV9DrIyGRW7ZsZ6fc99VtSUIuduiBswEC7KJO4KzmCK7bGsur9yVvJ0el4Ulwv0jWIwrEw5BiQ=,iv:kjpo47Q3Uo2SKBaiZjgc9OLPUVOaWA1N6p5AFVyFXzA=,tag:seE6ZvQbEP/Zif5TZT4a0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
