apiVersion: v1
kind: Namespace

metadata:
  name: hajimari
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization

metadata:
  name: hajimari
  namespace: flux-system

spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./workloads/hajimari"
  interval: 60m
  timeout: 3m
  retryInterval: 2m
  prune: true
  wait: true
