---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
  namespace: networking
type: Opaque
stringData:
  credential.json: >
    {
      "AccountTag": "${BOOTSTRAP_CLOUDFLARE_TUNNEL_ACCOUNT_TAG}",
      "TunnelSecret": "${BOOTSTRAP_CLOUDFLARE_TUNNEL_SECRET}",
      "TunnelID": "${BOOTSTRAP_CLOUDFLARE_TUNNEL_ID}",
      "TunnelName": "${BOOTSTRAP_CLOUDFLARE_TUNNEL_NAME}"
    }