apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: proxy
spec:
  serviceAccountName: tailscale
  initContainers:
    # In order to run as a proxy we need to enable IP Forwarding inside
    # the container. The `net.ipv4.ip_forward` sysctl is not allowlisted
    # in Kubelet by default.
  - name: sysctler
    image: busybox
    securityContext:
      privileged: true
    command: ["/bin/sh"]
    args:
      - -c
      - sysctl -w net.ipv4.ip_forward=1 net.ipv6.conf.all.forwarding=1
    resources:
      requests:
        cpu: 1m
        memory: 1Mi
  containers:
  - name: tailscale
    imagePullPolicy: Always
    image: "ghcr.io/tailscale/tailscale:latest"
    env:
    # Store the state in a k8s secret
    - name: TS_KUBE_SECRET
      value: tailscale-auth
    - name: TS_USERSPACE
      value: "false"
    - name: TS_AUTH_KEY
      valueFrom:
        secretKeyRef:
          name: tailscale-secret
          key: auth-key
          optional: true
    - name: TS_DEST_IP
      value: 10.43.96.35
    - name: TS_AUTH_ONCE
      value: "true"
    # - name: TS_EXTRA_ARGS
    #   value: --hostname=cluster
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx
#   namespace: networking
# spec:
#   serviceAccountName: tailscale
#   containers:
#   - name: nginx
#     image: nginx
#     resources:
#       limits:
#         cpu: 500m
#         memory: 500Mi
#   - name: ts-sidecar
#     imagePullPolicy: Always
#     image: "ghcr.io/tailscale/tailscale:latest"
#     resources:
#       limits:
#         cpu: 500m
#         memory: 500Mi
#     env:
#       # Store the state in a k8s secret
#     - name: TS_KUBE_SECRET
#       value: tailscale-auth
#     - name: TS_USERSPACE
#       value: "false"
#     - name: TS_AUTH_KEY
#       valueFrom:
#         secretKeyRef:
#           name: tailscale-secret
#           key: auth-key
#           optional: true
#     securityContext:
#       capabilities:
#         add:
#         - NET_ADMIN
# ---
# apiVersion: apps/v1
# kind: Deployment

# metadata:
#   name: tailscale
#   namespace: networking
#   labels:
#     app.kubernetes.io/name: tailscale
#     app.kubernetes.io/part-of: tailscale

# spec:
#   replicas: 1

#   selector:
#     matchLabels:
#       app.kubernetes.io/name: tailscale
#       app.kubernetes.io/part-of: tailscale

#   template:
#     metadata:
#       labels:
#         app.kubernetes.io/name: tailscale
#         app.kubernetes.io/part-of: tailscale

#     spec:
#       serviceAccountName: tailscale
#       terminationGracePeriodSeconds: 60
#       # initContainers:
#       #   # In order to run as a proxy we need to enable IP Forwarding inside
#       #   # the container. The `net.ipv4.ip_forward` sysctl is not allowlisted
#       #   # in Kubelet by default.
#       # - name: sysctler
#       #   image: busybox
#       #   securityContext:
#       #     privileged: true
#       #   command: ["/bin/sh"]
#       #   args:
#       #     - -c
#       #     - sysctl -w net.ipv4.ip_forward=1 net.ipv6.conf.all.forwarding=1
#       #   resources:
#       #     requests:
#       #       cpu: 1m
#       #     memory: 1Mi
#       containers:
#         - name: tailscale
#           image: ghcr.io/tailscale/tailscale:stable
#           securityContext:
#             privileged: true
#           #   capabilities:
#           #     add:
#           #       - NET_ADMIN
#           #       - NET_RAW
#           env:
#             - name: TS_USERSPACE
#               value: "false"
#             - name: TS_AUTH_KEY
#               valueFrom:
#                 secretKeyRef:
#                   name: tailscale-secret
#                   key: auth-key
#             - name: TS_KUBE_SECRET
#               value: tailscale-auth
#             - name: TS_DEST_IP
#               value: "10.43.0.60"
#             - name: TS_EXTRA_ARGS
#               value: --hostname=cluster
#           resources:
#             limits:
#               cpu: 500m
#               memory: 500Mi
