apiVersion: apps/v1
kind: Deployment

metadata:
  name: tailscale
  namespace: networking
  labels:
    app.kubernetes.io/name: tailscale
    app.kubernetes.io/part-of: tailscale
    app.kubernetes.io/version: 1.34.1

spec:
  replicas: 1
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app.kubernetes.io/name: tailscale
      app.kubernetes.io/part-of: tailscale

  template:
    metadata:
      labels:
        app.kubernetes.io/name: tailscale
        app.kubernetes.io/part-of: tailscale
        app.kubernetes.io/version: 1.34.1

    spec:
      serviceAccountName: tailscale

      terminationGracePeriodSeconds: 60

      containers:
        - name: tailscale

          imagePullPolicy: Always
          image: ghcr.io/tailscale/tailscale:v1.34.1

          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN

          env:
            - name: TS_USERSPACE
              value: "false"
            - name: TS_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-secret
                  key: auth-key
            - name: TS_KUBE_SECRET
              value: tailscale-auth
            - name: TS_DEST_IP
              value: 10.43.0.60
            - name: TS_EXTRA_ARGS
              value: --hostname=cluster

          resources:
            limits:
              cpu: 500m
              memory: 500Mi
