apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease

metadata:
  name: contour-private
  namespace: networking

spec:
  interval: 1m

  chart:
    spec:
      chart: contour
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 10.0.0

  values:
    contour:
      # Multiple deployments of contour will clash CRDs,
      # ensure only one chart manages them
      manageCRDs: true
      ingressClass:
        name: private
        default: false
    envoy:
      useHostPort: false
      service:
        type: ClusterIP
        externalTrafficPolicy: ""
        clusterIP: 10.43.0.60
      # sidecars:
      # - name: ts-sidecar
      #   imagePullPolicy: Always
      #   image: "ghcr.io/tailscale/tailscale:latest"
      #   serviceAccountName: tailscale
      #   env:
      #   - name: TS_KUBE_SECRET
      #     value: tailscale-auth
      #   - name: TS_USERSPACE
      #     value: "false"
      #   - name: TS_AUTH_KEY
      #     valueFrom:
      #       secretKeyRef:
      #         name: tailscale-secret
      #         key: auth-key
      #         optional: true
      #   securityContext:
      #     privileged: true
      #     capabilities:
      #       add:
      #       - NET_ADMIN
