apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: searxng
  namespace: searxng
spec:
  releaseName: searxng
  chart:
    spec:
      chart: searxng
      sourceRef:
        kind: HelmRepository
        name: searxng
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    searxng:
      config:
        general:
          instance_name: "Search"
        server:
          method: "GET"
        search:
          autocomplete: "google"